# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
gmail_username: 'teresanotificaciones@gmail.com'
gmail_password: 'bolsadetrabajo123'
development:
  secret_key_base: 6b45975e4c989c167fcccb4b3b6701c91d2881658273bda39aff16931ae2dfc788cf4ec4101850f289b2b2f1fe770b5c10754b72d42b1e48baf76a7b4a9b0a5c

test:
  secret_key_base: 6e2d475752e101ad6d5696399b67f61d361c16d6ff4958e9e4d95cd48cadb0bb320e767913720a8720f4445e0b01052693851dc83b85a9c6cbc4ff7d0e9d0c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
